#!/usr/bin/env perl
use strict;
use warnings;
use IPC::Open3;
use SMT::Agent::Constants;
use SMT::Agent::Utils;

sub jobhandler
{
  my ($jobtype, $jobid, $args, $verbose) =  @_;

  SMT::Agent::Utils::logger ("jobhandler for reboot called", $jobid);
  SMT::Agent::Utils::logger ("reboot runs jobid \"$jobid\"", $jobid);


  # check whether this handler can handle requested jobtype
  SMT::Agent::Utils::error ("wrong job handler: \"reboot\" cannot handle \"$jobtype\"", $jobid) if ( $jobtype ne "reboot" );


  #==  run shutdown ==

  my $command = "/bin/bash";
  my @cmdArgs;
  push (@cmdArgs, "-c");			
  push (@cmdArgs, "/sbin/shutdown -r +1 &");				

  foreach my $pack (@$packages)                                                             
  {                                                                                         
    push (@cmdArgs, $pack);
  }    

  (my $retval, my $stdout, my $stderr) = SMT::Agent::Utils::executeCommand ( $command, undef, @cmdArgs );

  if ( $verbose ne "true" )
  {
    $stdout="";
    $stderr="";
  }


  return (
    stdout => defined ( $stdout )? $stdout : "",
    stderr => defined ( $stderr )? $stderr : "",
    exitcode => $retval,
    success => ($retval == 0 ) ? "true" : "false",
    message => ($retval == 0 ) ? "reboot successfully triggered" : "reboot failed"
  );

}

SMT::Agent::Utils::logger ("successfully loaded handler for jobtype \"reboot\"");

return 1;

