#!/usr/bin/env perl
use strict;
use warnings;
use SMT::Agent::Constants;
use SMT::Agent::Utils;

sub jobhandler
{
  my ($jobtype, $jobid, $args, $verbose) =  @_;

  SMT::Agent::Utils::logger("jobhandler for servererror job called", $jobid);
  SMT::Agent::Utils::logger("servererror runs jobid \"$jobid\"", $jobid);
  SMT::Agent::Utils::error("wrong job handler: \"servererror\" cannot handle \"$jobtype\"", $jobid) unless ( $jobtype eq 'servererror' );

  return (
    stdout   => '',
    stderr   => "This job (id $jobid) caused a servererror when it was retrieved by the client.",
    exitcode => 1,
    success  => 'false',
    result   => undef,
    message  => "Error: Servererror when client retrieved the job."
  );

}

SMT::Agent::Utils::logger("successfully loaded handler for jobtype \"createjob\"");

return 1;

