--
-- drop timestamp from patchstatus information
--
ALTER TABLE Patchstatus DROP COLUMN PATCHSTATUS_DATE;

--
-- change patch counters back to not be NULL
--
ALTER TABLE Patchstatus MODIFY COLUMN PKGMGR INTEGER UNSIGNED NOT NULL default 0;
ALTER TABLE Patchstatus MODIFY COLUMN SECURITY INTEGER UNSIGNED NOT NULL default 0;
ALTER TABLE Patchstatus MODIFY COLUMN RECOMMENDED INTEGER UNSIGNED NOT NULL default 0;
ALTER TABLE Patchstatus MODIFY COLUMN OPTIONAL INTEGER UNSIGNED NOT NULL default 0;
