#!/bin/sh
#
# smt-repeated-register


SMTCMD=/usr/sbin/smt
. /etc/smt.d/smt-cron.conf

if [ -x ${SMTCMD}-register ]
then
    ${SMTCMD}-register ${REGISTER_PARAMS}
else
    echo "WARNING: Could not find the SMT binary ${SMTCMD}-register"
    echo "         Please make sure SMT is properly installed."
fi

# in cronjobs always do an exit 0 - even on errors - exit 1 only in case of real panic
exit 0
