#!/bin/sh
#
# smt-logrun
#     Wrapper to run smt commands with proper logging

if [ -z $1 ]
then
  echo "No jobs found to be processed"
  exit 1
fi


SMTCMD=/usr/sbin/smt
JOBS=$@
LOGDIR="/var/log"

if [ -x ${SMTCMD} ]
then

  for JOB in ${JOBS}
  do
    if [ -x ${SMTCMD}-${JOB} ]
    then
      if [ ${JOB} = "register" ]
      then
        ${SMTCMD}-${JOB} -r -L ${LOGDIR}/smt-${JOB}.log
      else
        ${SMTCMD}-${JOB} -L ${LOGDIR}/smt-${JOB}.log
      fi
    else
      echo "WARNING: Could not find the SMT binary ${SMTCMD}-${JOB}"
      echo "         Please make sure SMT is properly installed."
    fi
  done

else
  echo "Could not find the SMT core binary. Your SMT installation seems to be broken."
  exit 1
fi

exit 0
