#!/bin/sh
#
# smt-run-cleanup-jobqueue
# This script calls the clean-up script of the SMT JobQueue.

PATH="/sbin:/usr/sbin:/usr/bin:/bin"

. /etc/smt.d/smt-cron.conf

# source the profile to get the proxy settings
. /etc/profile.d/profile.sh

if [ -x /usr/lib/SMT/bin/smt-jobqueue-cleanup ]
then
    /usr/lib/SMT/bin/smt-jobqueue-cleanup ${JOBQUEUECLEANUP_PARAMS}
else
    echo "WARNING: Could not find the SMT binary smt-jobqueue-cleanup"
    echo "         Please make sure SMT is properly installed."
fi

# in cronjobs always do an exit 0 - even on errors - exit 1 only in case of real panic
exit 0

