#!/bin/sh
#
#
# smt-daily
# This script runs organizational commands for the SMT service.
# It syncs the local SMT with the Novell NCC, creates a daily report
# and updates the mirrored installation and update sources.

JOBS="ncc-sync report mirror"
SMTLOGRUN=/usr/lib/SMT/bin/smt-logrun

${SMTLOGRUN} ${JOBS}

if [ $? != 0 ]
then
  echo "Warning: Errors occurred within smt-daily run"
fi

# in cronjobs always do an exit 0 - even on errors - exit 1 only in case of real panic
exit 0
