create table MergedCatalogs(
  SOURCECATALOGID INT NOT NULL,
  TARGETCATALOGID INT NOT NULL,
  LASTMERGE       TIMESTAMP,
  PRIMARY KEY (SOURCECATALOGID, TARGETCATALOGID)
);

-- allow NULL for EXTURL and EXTHOST
alter table Catalogs
  change column EXTURL EXTURL VARCHAR(300),
  change column EXTHOST EXTHOST VARCHAR(300);

