
ALTER TABLE Catalogs drop PRIMARY KEY;

ALTER TABLE Catalogs ADD PRIMARY KEY ID(ID);

DROP INDEX ID ON Catalogs;

alter table Catalogs add unique key CID_SRC (CATALOGID, SRC);

ALTER TABLE Catalogs ADD COLUMN AUTOREFRESH CHAR(1) NOT NULL DEFAULT 'Y';
