--------------------------------------------------------------------
-- Product_Dependencies
--------------------------------------------------------------------
-- select PARENT_PRODUCT_ID, CHILD_PRODUCT_ID
-- from activator.NNW_PRODUCT_DEPENDENCIES 
-- where PARENT_PARTNUMBER is NULL
--------------------------------------------------------------------
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(21, 141);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(21, 142);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(22, 141);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(22, 142);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(23, 141);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(23, 142);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(24, 141);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(24, 142);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(25, 141);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(25, 142);


INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(431, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(432, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(433, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(434, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(435, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(446, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(447, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(448, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(449, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(450, 498);

INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(431, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(432, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(433, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(434, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(435, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(446, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(447, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(448, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(449, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(450, 499);

INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(416, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(417, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(418, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(419, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(420, 498);

INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(416, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(417, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(418, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(419, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(420, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(720, 499);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(721, 499);

INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(722, 498);
INSERT INTO ProductDependencies(PARENT_PRODUCT_ID, CHILD_PRODUCT_ID)
  VALUES(722, 499);
