#!/usr/bin/perl
###########################################################################
## Copyright (c) 2007 Novell Inc.
###########################################################################

#
# exit codes in "smt-db":
#
# 1 : cannot disable echo mode 
# 2 : Cannot read the SMT configuration file
# 3 : Invalid Database configuration. Missing value for DB/config
# 4 : Cannot connect to database (wrong mysql root password?)
# 5 : SMT database already exists
# 6 : Passwords do not match. (for smt user)
# 7 : Cannot create Database smt
#
# 20: Could not connect to the database(with smt user - wrong password?)
# 21: Database migration failed

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");

use SMT::Utils;
use DBIx::Migration::Directories;
use DBIx::Transaction;


use Locale::gettext ();
use POSIX ();     # Needed for setlocale()
POSIX::setlocale(&POSIX::LC_MESSAGES, "");

sub db_connect
{
    my $cfg = new Config::IniFiles( -file => "/etc/smt.conf" );
    if(!defined $cfg)
    {
        # FIXME: is die correct here?
        print STDERR sprintf(__("Cannot read the SMT configuration file: %s\n"), @Config::IniFiles::errors);
	exit 2;
    }
    
    my $config = $cfg->val('DB', 'config');
    my $user   = $cfg->val('DB', 'user');
    my $pass   = $cfg->val('DB', 'pass');
    if(!defined $config || $config eq "")
    {
        # FIXME: is die correct here?
        print STDERR __("Invalid Database configuration. Missing value for DB/config.\n");
	exit 3;
    }
     
    my $dbh    = DBIx::Transaction->connect($config, $user, $pass, {RaiseError => 1, AutoCommit => 1});

    return $dbh;
}

sub help
{
    print __("\nSMT database maintenance tool\n");
    print __("Available commands:");
    print "  help : ".__("show help\n");
    print "  init : ".__("initialize or upgrade database\n");
    print "  setup: ".__("setup the database\n");
    exit 0;
}

sub migrate
{
    my $dbh;
    if ( not $dbh=db_connect() )
    {
        print STDERR __("ERROR: Could not connect to the database.\n");
	return 20;
    }


    my $m = DBIx::Migration::Directories->new(
        base                    => '/usr/share/schemas',
        schema                  => 'smt',
        desired_version_from    => 'SMT',
        dbh                     => $dbh
        );
  
    eval 
    {
        $m->full_migrate;
    };
    if($@)
    {
	print STDERR "Installing database failed! $@\n";
	return 21;
    }
    return 0;
}

sub setup
{
    my $username = "root";
    my $password = "";
    my $smtuser = "smt";
    my $smtpass = "";
    
    print "mysql password for user $username: ";
    system("stty -echo") == 0 or do
    {
	   print STDERR "Can not disable echo mode: $!\n";
	   return 1;
    };
    chomp($password = <STDIN>);
    system("stty echo");
    print "\n";
    
    my $cfg = new Config::IniFiles( -file => "/etc/smt.conf" );
    if(!defined $cfg)
    {
        print STDERR sprintf(__("Cannot read the SMT configuration file: %s\n"), @Config::IniFiles::errors);
	return 2;
    }
    
    my $config = $cfg->val('DB', 'config');
    if(!defined $config || $config eq "")
    {
        print STDERR __("Invalid Database configuration. Missing value for DB/config.\n");
	return 3;
    }
    $config =~ s/database=smt/database=/;
    
    my $dbh    = undef;
    eval {
    	$dbh    = DBI->connect($config, $username, $password, {RaiseError => 1, AutoCommit => 1});
    };
    if($@)
    {
	    print STDERR "Cannot connect to database: $@\n";
	    return 4;
    }
    
    my $r = $dbh->selectcol_arrayref("show databases");
    my $found = 0;
    
    foreach (@{$r})
    {
        $found = 1 if($_ eq "smt");
    }
    
    if($found)
    {
        print STDERR "SMT database already exists.\n";
	return 5;
    }
    
    print "Enter a new username for the smt database: ";
    chomp($smtuser = <STDIN>);
    
    print "New password for user $smtuser: ";
    system("stty -echo") == 0 or do {
	   print STDERR "Can not disable echo mode: $!\n";
	   return 1;
    };
    chomp($smtpass = <STDIN>);
    system("stty echo");
    print "\n";
    
    my $smtpassV = "";
    
    print "Repeat password for user $smtuser: ";
    system("stty -echo") == 0 or do {
	   print STDERR "Can not disable echo mode: $!\n";
	   return 1;
    };
    chomp($smtpassV = <STDIN>);
    system("stty echo");
    print "\n";
    
    if($smtpass ne $smtpassV)
    {
        print STDERR "Passwords do not match.\n";
	return 6;
    }

    $r = $dbh->do("create database if not exists smt");
    if($r != 1)
    {
        print STDERR "Cannot create Database smt.\n";
	return 7;
    }
    
    $r = $dbh->do("grant all on smt.* to $smtuser\@localhost identified by '$smtpass'");
    
    $cfg->setval('DB', 'user', $smtuser);
    $cfg->setval('DB', 'pass', $smtpass);
    $cfg->WriteConfig("/etc/smt.conf");
    
    return 0;
}


if (defined $ARGV[0] ) 
{
    my $cmd = shift(@ARGV);
    #print "cmd: $cmd\n";
    if ( $cmd eq "help" )
    {

    }
    elsif ( $cmd eq "init" )
    {
        migrate();
    }
    elsif ( $cmd eq "setup" )
    {
        my $ret = setup();
	if($ret != 0)
	{
		exit $ret;
	}
        $ret = migrate();
	if($ret != 0)
	{
	        exit $ret;
	}
    }
}
else
{
    help();
}

exit 0;





