#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use YEP::CLI;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

if (defined $ARGV[0]  && $ARGV[0] eq "failing") 
{
  exit 1
}

if ( defined $ARGV[0]  && $ARGV[0] eq "list-products" )
{
  YEP::CLI::listProducts();
}
elsif ( defined $ARGV[0]  && $ARGV[0] eq "list-registrations" )
{
  YEP::CLI::listRegistrations()
}
elsif ( defined $ARGV[0]  && $ARGV[0] eq "test" )
{
  YEP::CLI::setMirrorableCatalogs()
}
else
{
  print "$0" . __("list-products => Show products\n");
  print __("Nothing to do\n");
  exit 0;
}
