#!/usr/bin/perl
###########################################################################
## Copyright (c) 2007 Novell Inc.
###########################################################################

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use SMT::CLI;
use SMT::Utils;
use File::Basename;
use File::Find;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

sub help
{
    print __("show help\n");
    my @files;
    find( sub { push(@files, $1) if $_ =~ /smt\-(.+)/; }, "/usr/sbin");
    

    print "YaST Enterprise Proxy. (c)2007 Novell Inc.\n\n";

    foreach my $cmd (@files)
    {
      print basename($0) . " $cmd\n";
    }

    print __("\nUse smt help <command> for more help\n");
    exit 0;
}

sub executeCommand
{
  my $name = shift;
  my @options = @_;

  my $exec = "/usr/sbin/smt-$name";
  my $cmd = "$exec ";
  foreach (@options)
  {
    if($_ eq "")
    {
      $cmd .= "'' ";
    }
    else
    {
      $cmd .= "$_ ";
    }
  }

  #print "execute '$cmd'\n";
  if ( -e $exec )
  {
      system($cmd);
  }
  else
  {
    die "$cmd command not installed\n";
  }
}

if (defined $ARGV[0] ) 
{
    my $cmd = shift(@ARGV);
    #print "cmd: $cmd\n";
    if ( $cmd eq "help" || $cmd eq "-h" || $cmd eq "--help")
    {
        if (defined $ARGV[0] ) 
        {
            my $targethelp = shift(@ARGV);
            executeCommand($targethelp,"-h");
        }
        else
        {
            help();
        }
    }
    else
    {
        executeCommand($cmd, @ARGV)
    }
}
else
{
    help();
}

exit 0;
