#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use SMT::CLI;
use SMT::Utils;
use File::Basename;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

my $mirrorable;
my $domirror;
my $verbose;
my $used;
my $catstat;
my $help;

use Getopt::Long;
&Getopt::Long::Configure( 'pass_through', 'no_autoabbrev');
&Getopt::Long::GetOptions(
         'used|u' => \$used,
         'catstat|c' => \$catstat,
         'verbose|v' => \$verbose,
         'help|h' => \$help
);

if ( defined $help and ( $help == 1 ) )
{
  print basename($0) . " : " . __("list known products\n");
  print "    -used       (-u) : " . __("show only used products\n");
  print "    -catstat    (-c) : " . __("show catalog status. Are all catalogs localy mirrored, which are required for this product?\n");
  print "    -verbose    (-v) : " . __("show detailed product information\n");
  exit 0;
}

SMT::CLI::listProducts(verbose => $verbose, used => $used, catstat => $catstat);
