#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use SMT::CLI;
use SMT::Utils;
use File::Basename;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

my $mirrorable;
my $domirror;
my $verbose;
my $help;

use Getopt::Long;
&Getopt::Long::Configure( 'pass_through', 'no_autoabbrev');
&Getopt::Long::GetOptions(
         'mirrorable|m'         => \$mirrorable,
         'domirror|d'        => \$domirror,
         'verbose|v'        => \$verbose,
         'help|h' => \$help
);

if ( defined $help and ( $help == 1 ) )
{
  print basename($0) . " : " . __("list known catalogs\n");
  print "    -mirrorable (-m) : " . __("only mirrorable catalogs\n");
  print "    -domirror   (-d) : " . __("only catalogs set to be mirrored\n");
  print "    -verbose    (-v) : " . __("show detailed catalog information\n");
  exit 0;
}

my %opts = ( );
SMT::CLI::listCatalogs(mirrorable => $mirrorable, domirror => $domirror, verbose => $verbose);
