#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use SMT::CLI;
use SMT::Utils;
use File::Basename;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

my $mirrorable;
my $domirror;
my $verbose;
my $used;
my $catstat;
my $help;

use Getopt::Long;
&Getopt::Long::Configure( 'pass_through', 'no_autoabbrev');
&Getopt::Long::GetOptions(
         'used|u' => \$used,
         'catstat|c' => \$catstat,
         'verbose|v' => \$verbose,
         'help|h' => \$help
);

if ( defined $help and ( $help == 1 ) )
{
  print basename($0) . " : " . __("list known products\n");
  print "    -used       (-u) : " . __("show only used products\n");
  print "    -catstat    (-c) : " . __("show catalog status. Are all catalogs localy mirrored, which are required for this product?\n");
#  print "    -verbose    (-v) : " . __("show detailed product information\n");
  print "   --help            (-v) :     " . __("show this help\n");
  exit 0;
}

SMT::CLI::listProducts(verbose => $verbose, used => $used, catstat => $catstat);

exit 0;

#
# Manpage
#

=head1 NAME

smt list-products -  

=head1 SYNOPSIS

smt list-products [options]

=head1 DESCRIPTION

C<smt list-products> shows information about known products allowing filtering by varous criteria.

=head1 OPTIONS

=item -used -u

Shows only used products.

=item -catstat -c

Shows catalog status. Are all catalogs localy mirrored, which are required for this product?.

=head1 AUTHORS and CONTRIBUTORS

Duncan Mac-Vicar Prett, Lukas Ocilka, Jens Daniel Schmidt, Michael Calmer

=head1 LICENSE

Copyright (c) 2008 SUSE LINUX Products GmbH, Nuernberg, Germany.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 675 Mass
Ave, Cambridge, MA 02139, USA.

=cut
