#!/usr/bin/perl
###########################################################################
## Copyright (c) 2007 Novell Inc.
###########################################################################

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use YEP::CLI;
use YEP::Utils;
use File::Basename;
use File::Find;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

sub help
{
    print __("show help\n");
    my @files;
    find( sub { push(@files, $1) if $_ =~ /yep\-(.+)/; }, "/usr/sbin");
    

    print "YaST Enterprise Proxy. (c)2007 Novell Inc.\n\n";

    foreach my $cmd (@files)
    {
      print basename($0) . " $cmd\n";
    }

    print __("\nUse yep help <command> for more help\n");
    exit 0;
}

sub executeCommand
{
  my $name = shift;
  my @options = @_;

  my $exec = "/usr/sbin/yep-$name";
  my $cmd = "$exec " . join(" ", @options);
  #print "execute '$cmd'\n";
  if ( -e $exec )
  {
      system($cmd);
  }
  else
  {
    die "$cmd command not installed\n";
  }
}

if (defined $ARGV[0] ) 
{
    my $cmd = shift(@ARGV);
    #print "cmd: $cmd\n";
    if ( $cmd eq "help" )
    {
        #print "2foo\n";
        my $targethelp = shift(@ARGV);
        executeCommand($targethelp,"-h");
    }
    else
    {
      executeCommand($cmd, @ARGV)
    }
}
else
{
    help();
}

exit 0;
