#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use YEP::CLI;

my $mirrorable;
my $domirror;
my $help;

use Getopt::Long;
&Getopt::Long::Configure( 'pass_through', 'no_autoabbrev');
&Getopt::Long::GetOptions(
         'help|h' => \$help
);

if ( defined $help and ( $help == 1 ) )
{
  print "Reset all catalogs mirrorable flag. Syncs with NCC and check for mirrorable catalogs\n";
  exit 0;
}

YEP::CLI::resetCatalogsStatus();
YEP::CLI::setMirrorableCatalogs();


