#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use YEP::CLI;
use File::Basename;

my $mirrorable;
my $domirror;
my $verbose;
my $help;

use Getopt::Long;
&Getopt::Long::Configure( 'pass_through', 'no_autoabbrev');
&Getopt::Long::GetOptions(
         'mirrorable|m'         => \$mirrorable,
         'domirror|d'        => \$domirror,
         'verbose|v'        => \$verbose,
         'help|h' => \$help
);

if ( defined $help and ( $help == 1 ) )
{
  print basename($0) . " : list known catalogs\n";
  print "    -mirrorable (-m) : only mirrorable catalogs\n";
  print "    -domirror   (-d) : only catalogs set to be mirrored\n";
  print "    -verbose    (-v) : show detailed catalog information\n";
  exit 0;
}

my %opts = ( );
YEP::CLI::listCatalogs(mirrorable => $mirrorable, domirror => $domirror, verbose => $verbose);
