#!/usr/bin/perl

use strict;
use warnings;
use lib ("/srv/www/perl-lib/");
use YEP::CLI;
use File::Basename;

my $mirrorable;
my $domirror;
my $verbose;
my $help;

use Getopt::Long;
&Getopt::Long::Configure( 'pass_through', 'no_autoabbrev');
&Getopt::Long::GetOptions(
         'verbose|v' => \$verbose,
         'help|h' => \$help
);

if ( defined $help and ( $help == 1 ) )
{
  print basename($0) . " : list active registrations\n";
  print "    -verbose    (-v) : show detailed registration information\n";
  exit 0;
}

YEP::CLI::listRegistrations(verbose => $verbose);
