#!/usr/bin/perl -w

###########################################################################
## Copyright (c) 2007 SUSE LINUX Products GmbH, Nuernberg, Germany.
###########################################################################

BEGIN
{
    if(exists $ENV{https_proxy})
    {
        # required for Crypt::SSLeay HTTPS Proxy support
        $ENV{HTTPS_PROXY} = $ENV{https_proxy};
    }
}


use strict;
use YEP::Utils;
use YEP::NCCRegTools;
use Getopt::Long;
use LWP::UserAgent;
use Crypt::SSLeay;
#use XML::Writer;
use File::Basename;
use Data::Dumper;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");


my $debug = 0;
my $help  = 0;

my $uri       = "";
my $yepguid   = "";
my $yepsecret = "";


my $result = GetOptions ("debug|d"     => \$debug,
                         "help|h"      => \$help
                        );

if($help)
{
    print basename($0) . __(" [OPTIONS]\n");
    print __("Register all clients at NCC which are currently not registered\n");
    print __("or which data changed since the last registration.\n");
    print "\n";
    print __("Options:\n");
    print "--debug -d       " . __("enable debug mode\n");
    print "--help -h        " . __("show this message\n");
    exit 0;
}


my $useragent = LWP::UserAgent->new(keep_alive => 1);
$useragent->protocols_allowed( [ 'https' ] );
$useragent->default_headers->push_header('Content-Type' => 'text/xml');
push @{ $useragent->requests_redirectable }, 'POST';

if(!YEP::Utils::openLock("yep-register"))
{
    print __("Registration process is still running.\n");
    exit 0;
}

my $dbh = undef;

$dbh = YEP::Utils::db_connect();

if(!$dbh)
{
    if(!YEP::Utils::unLock("yep-register"))
    {
        print STDERR __("Cannot remove lockfile.\n");
    }
    die __("Cannot connect to database");
}

eval
{
    my $nccreg = YEP::NCCRegTools->new(debug => $debug, useragent => $useragent, dbh => $dbh);
    my $err = $nccreg->NCCRegister();
    if($err != 0)
    {
        if(!YEP::Utils::unLock("yep-register"))
        {
            print STDERR __("Cannot remove lockfile.\n");
        }
        exit 1;
    }
};
if($@)
{
    if(!YEP::Utils::unLock("yep-register"))
    {
        print STDERR __("Cannot remove lockfile.\n");
    }
    exit 1;
}

if(!YEP::Utils::unLock("yep-register"))
{
    print STDERR __("Cannot remove lockfile.\n");
}
exit 0;



