--
-- add timestamp for patchstatus information
--
ALTER TABLE Patchstatus ADD COLUMN PATCHSTATUS_DATE TIMESTAMP default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

--
-- change patch counters to be able to be NULL
--
ALTER TABLE Patchstatus MODIFY COLUMN PKGMGR INTEGER UNSIGNED;
ALTER TABLE Patchstatus MODIFY COLUMN SECURITY INTEGER UNSIGNED;
ALTER TABLE Patchstatus MODIFY COLUMN RECOMMENDED INTEGER UNSIGNED;
ALTER TABLE Patchstatus MODIFY COLUMN OPTIONAL INTEGER UNSIGNED;
